# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -qq
    apt-get install -y $(< /vagrant/packages)
    apt-get clean && apt-get autoclean
    Rscript -e 'install.packages("Rcpp",    repos="https://cran.r-project.org")'
    Rscript -e 'install.packages("RInside", repos="https://cran.r-project.org")'
    rm -rf /var/lib/apt/lists/*
    localedef -i en_US -f UTF-8 en_US.UTF-8
  SHELL

end
