# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "fedora/28-cloud-base"
  config.vm.hostname = "root-fedora"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
  end

  config.ssh.insert_key = true
  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    yum install -y root python3-root
    yum clean all
  SHELL
end
